name: Interactive Shell

on:
  workflow_dispatch:
    inputs:
      raw_file:
        description: "Raw file URL that'll be run in the shell upon connecting"
        required: true
        default: 'https://raw.githubusercontent.com/c0dem0de/TUIs/refs/heads/main/app.py'

jobs:
  interactive_shell:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Setup Locale
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y tmate curl wget neovim bash python3-urwid python3-pyfiglet
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

      - name: Modify Bash shell setup with custom variable
        run: |
          # Get the custom URL from the workflow input
          export MY_CUSTOM_URL='${{ github.event.inputs.raw_file }}'
          echo 'The custom URL is: $MY_CUSTOM_URL'

          # Extract the filename and extension from the URL
          filename=$(basename "$MY_CUSTOM_URL")

          # Download the file using wget with the extracted filename
          wget "$MY_CUSTOM_URL" -O "$filename"
          ls -l "$filename"

      - name: Start tmate session
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US.UTF-8

          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          tmate -S /tmp/tmate.sock -c "bash $filename"
          echo "SSH: ${TMATE_SSH}"
          echo "Use the above SSH command to connect to the tmate session."

          while true; do
            echo "Keeping tmate session alive..."
            sleep 300
            tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          done
