name: Interactive Shell

on:
  workflow_dispatch:
    inputs:
      raw_file:
        description: "Raw file URL that'll be run in the shell upon connecting"
        required: true
        default: "https://raw.githubusercontent.com/c0dem0de/TUIs/refs/heads/main/app.py"

jobs:
  interactive_shell:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Setup Locale
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y tmate curl wget neovim bash
          sudo apt-get install -y python3-urwid python3-pyfiglet
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

      - name: Setup and Start Interactive Session
        run: |
          # Download the Python script
          export MY_CUSTOM_URL='${{ github.event.inputs.raw_file }}'
          FILENAME=$(basename "$MY_CUSTOM_URL")
          wget "$MY_CUSTOM_URL" -O "$FILENAME"

          # Create a wrapper script that:
          # 1) Runs the Python script
          # 2) Immediately forces the tmate session to terminate
          cat > wrapper.sh <<EOF
          #!/bin/bash
          python3 "$FILENAME"
          # Forcefully kill the tmate session when Python completes
          tmate -S /tmp/tmate.sock kill-session
          EOF
          chmod +x wrapper.sh

          # Configure tmate to hide status lines
          mkdir -p ~/.tmate
          cat > ~/.tmate.conf <<EOF
          set -g tmate-server-host "ssh.tmate.io"
          set -g tmate-server-port 22
          set -g tmate-server-rsa-fingerprint "SHA256:Hthk2T/M/Ivqfk1YYUn5ijC2Att3+UPzD7Rn72P5VWs"
          set -g tmate-server-ecdsa-fingerprint "SHA256:8PtXBC5Hbq3UQGuXUYZpZQtLb0t+0dPp9Zs1t6CYcis"
          set -g tmate-identity ""
          set -g status off
          set -g status-interval 0
          EOF

          # Launch tmate running the wrapper script in a detached session
          tmate -S /tmp/tmate.sock new-session -d "./wrapper.sh"
          tmate -S /tmp/tmate.sock wait tmate-ready

          echo "Connect via SSH using:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

          # Rather than checking for the session, we allow the wrapper to kill it.
          # Once the script ends, the session terminates automatically.
